language: erlang
env:
  - LUA=""
  - LUA="luajit"
branches:
  only:
    - master
    - develop
install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted
  - sudo luarocks install luasocket
  - sudo luarocks install luacrypto
script: "busted spec"

#notifications:
#  webhooks:
#    - http://my-url/travis-results
#  recipients:
#    - engineering@company.com
#  email:
#    on_success: change
#    on_failure: always
