language: erlang
env:
    - LUA=""
branches:
    only:
        - master
        - develop
    install:
        - sudo apt-get install luarocks
        - sudo apt-get install libyaml-dev
        - sudo rm -rf ~/.cache/luarocks
        - sudo luarocks install luafilesystem
        - sudo luarocks install busted
        - sudo luarocks install luasocket
        - sudo luarocks install luaossl
        - sudo luarocks install lyaml YAML_LIBDIR=/usr/lib/x86_64-linux-gnu
script: busted spec
notifications:
  slack:
    secure: T4b0kjRp3Qa0DuXUsMGxxN1g3rNFhzwFdPZb0r8nhSPaIg/2s26vrD5mD8TzEdNW6lBCwy48ruvMEfB1cv7Wcz7LC8O6UGiLF3wEUALd1G+oBDBKWNRSIbnLnANTJDgXsZE+aQK3eb9fik/T/XFc/V2btq0ApOwZO/2L/sZFsdY=
