language: erlang
env:
  - LUA=""
#  - LUA="luajit"
branches:
  only:
    - master
    - develop
install:
  #  - sudo apt-get install apt-file
  - sudo apt-get install luarocks
  - sudo apt-get install libyaml-dev
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted
  - sudo luarocks install luasocket
  - sudo luarocks install luacrypto
  - sudo luarocks install lyaml YAML_LIBDIR=/usr/lib/x86_64-linux-gnu
script: "busted spec"

#notifications:
#  webhooks:
#    - http://my-url/travis-results
#  recipients:
#    - engineering@company.com
#  email:
#    on_success: change
#    on_failure: always
